filokseniaProject/cart/urls.py
from django.urls import path
from . import views
app_name="cart"
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

filokseniaProject/filoksenia/urls.py
from django.urls import path

from filoksenia import views
app_name='filoksenia'
urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('slug/<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProDetail,name='ProCatDetail')
]

filokseniaProject/filokseniaProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('filoksenia.urls')),
    path('search_app/',include('search_app.urls')),
    path('cart/',include('cart.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

filokseniaProject/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns=[
    path('',views.searchResult,name='SearchResult'),
]

filokseniaProject/cart/models.py
from django.db import models
from filoksenia.models import Product

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=True)
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return '{}'.format(self.product)
    

filokseniaProject/filoksenia/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    objects = None
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name', )
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('filoksenia:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):

    objects = None
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='Product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('filoksenia:ProCatDetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name', )
        verbose_name='product'
        verbose_name_plural='products'



    def __str__(self):
        return '{}'.format(self.name)

filokseniaProject/search_app/models.py
from django.db import models

# Create your models here.

filokseniaProject/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from filoksenia.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            # cart_item.subtotal = cart_item.quantity * cart_item.product.price
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save(),
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            # sub_total=cart_item.product.price * cart_item.product.quantity
            total+=(cart_item.product.price * cart_item.quantity)
            counter+=cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

filokseniaProject/filoksenia/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from filoksenia.models import Category, Product


# Create your views here.

def allProdCat(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        product_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        product_list=Product.objects.all().filter(available=True)
    paginator=Paginator(product_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})



# to create details of Product if I click the Product Name


def ProDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

filokseniaProject/search_app/views.py
from django.shortcuts import render

from filoksenia.models import Product
from django.db.models import Q

# Create your views here.
def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query)|Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

filokseniaProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/fc51e437b8.js" crossorigin="anonymous"></script>


    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="bg_color">
<div class="container-fluid">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block body %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>




<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

filokseniaProject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
      This is the cartpage, proceed to review your items and place the order
{% endblock %}
{% block title %}
  Cart - filoksenia Company PVT LTD
{% endblock %}
{% block body %}
{% if not cart_items %}
<div>
    <div class="text-center" style="color:white;">
        <br>
        <h1 class="text-center my_title">
            You shopping cart is empty
        </h1>
        <br>
        <p class="text-center">
            please click <a href="{% url 'filoksenia:allProdCat' %}"> Here </a> to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my-custom-table">
            <thead class="my-custom-thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom-image" style="width:100px; height:100px;" ></a>
                </td>
                <td class="text-bold">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Price:₹{{cart_item.product.price}}
                    <br>
                    Qty:{{cart_item.quantity}}
                </td>
<!--                <td>-->

<!--                    ₹-->

<!--                </td>-->
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-plus"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product_id %}" class="custom_a"><i class="fa-solid fa-trash"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product_id %}" class="custom_a"><i class="fa-solid fa-trash"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my-cutsom-table">
            <thead class="my-custom-thead">
            <tr>
                <td>
                    Checkout
                </td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart items before proceeding with the order payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    your total is <strong>₹{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'filoksenia:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
            <a href="{% url 'filoksenia:allProdCat' %}" class="btn btn-success btn-block my_custom_buttom">Make payment</a>
        {% endif %}
        </div>

    </div>

    </div>

{% endblock %}

filokseniaProject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {% if category %}
          {{category.description|truncatewords:155}}
     {% else %}
          Welcome To filoksenia where you can explore THE TIME TRAVEL
     {% endif %}
{% endblock %}
{% block title %}
     {% if category %}
         {{category.name}}-filoksenia
     {% else %}
         See our New Collections - filoksenia
     {% endif %}
{% endblock %}
{% block body %}
     {% if category %}
         <div>
             <div class="row my_row_class">
             <div class="mx_auto">
                 <p><a href="{% url 'filoksenia:allProdCat' %}"> Our Product Collections</a></p>
             </div>
                 </div>
         </div>
     {% endif %}

{% if category %}
<div class="mx_auto">
     <div style="text-align: center;">
         <img class="my_image my_image_padding" style="width: 450px; height: 450px;" src="{{ category.image.url }}" alt="{{category.name}}" >
     </div>
</div>
<br>
<div class="text_colour" >
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
    {% else %}
<div>
    <img class="ban_size" src="{% static 'img/banner1.png' %}" alt="our product" width="1250px;">
</div>
<br>
<div class="text_colour">
    <h1 class="text-center my_title"> Our Product Collections</h1>
    <p class="text-justify">A watch is a timekeeping device worn on the wrist or carried in a pocket. It combines functionality and fashion,
        allowing you to keep track of time while adding a stylish accessory to your outfit.
        Watches come in various types, including analog, digital, chronograph, hybrid, smart,
        and fitness watches, catering to different preferences and needs.
        From classic designs to modern innovations, watches are not only practical but also make a fashion statement.
        Whether you're looking for a simple timepiece or a high-tech smartwatch, there's a watch out there for everyone.</p>
</div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="min-width:18rem;background:#F7F5F5;">
                <a href ="{{product.get_url}}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}" style="width: 350px; height: 400px;" ></a>
                <div class="card-body text_colour">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <br>
        <div class = "text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm{% if products.number == pg %} active {% endif%}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

filokseniaProject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy;AMK tech Pvt Ltd. All Rights Reserved</p>
</div>

filokseniaProject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'filoksenia:allProdCat' %}"><img src="{% static 'img/logo1.png' %}" alt="logimage" style="width: 350px; height: 350px;"></a>
    </center>
</header>

filokseniaProject/templates/navbar.html
<nav class="navbar navbar-expand-lg  bg-custom-color ban_size">
  <div class="container-fluid ">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'filoksenia:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'filoksenia' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item " href="{% url 'filoksenia:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item " href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'cart:cart_detail' %}" ><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success text-white" type="submit"><i class="fa-solid fa-magnifying-glass fa-beat-fade"></i></button>
      </form>
    </div>
  </div>
</nav>

filokseniaProject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
          {{product.description|truncatewords:155}}
{% endblock %}
{% block title %}
     {% if category %}
         {{product.name}}-filoksenia
     {% endif %}
{% endblock %}
{% block body %}

<div class="row my_prod_row_class">
    <div class="mx_auto text_colour">
        <p><a href="{% url 'filoksenia:allProdCat' %}"> Home</a>|<a href = "{{ product.category.get_url }}">|{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="width: 650px; height: 650px;">
        </div>
    </div>
    <div>
        <div class="text_colour col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>₹{{product.price}}</p>
            <p class="my_title"> Product description </p>
            <p class="text-justify my_prod_text"> {{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b> Out of Stock </b></p>
            {% else %}
            <a class="btn-btn-secondary" href ="{% url 'cart:add_cart' product.id %} "> Add to Cart </a>
            {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

filokseniaProject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    we have variety of products
{% endblock %}
{% block title %}
   Search
{% endblock %}
{% block body %}
<div>
    <p class="text-center my_search_text" style="color:white;">You have searched for :<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="min-width:18rem;background:#F7F5F5;">
                <a href ="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width: 350px; height: 400px;" ></a>
                <div class="card-body text_colour">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx_auto">
            <p class="text-center my_search_text" style="color:white;"> 0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}